version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: tacuong
      POSTGRES_PASSWORD: 12345678
    ports:
      - 5432:5432
    volumes:
      - ./.docker/data/postgres:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: tacuong
      KC_DB_PASSWORD: 12345678
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    command:
      - start-dev
    volumes:
      - ./themes/custom-theme:/opt/keycloak/themes/custom-theme
    depends_on:
      - postgres
