version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: tacuong
      POSTGRES_PASSWORD: 12345678
    ports:
      - 5432:5432
    volumes:
      - ./.docker/data/postgres:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_USER: tacuong
      DB_PASSWORD: 12345678
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    volumes:
      - ./themes/custom:/opt/jboss/keycloak/themes/custom
    depends_on:
      - postgres
