version: "3.8"

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: tacuong
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - ./.docker/data/minio:/data
    command: server --console-address :9001 /data
